<template><h1 id="centos-rhel-7-booting-process" tabindex="-1"><a class="header-anchor" href="#centos-rhel-7-booting-process" aria-hidden="true">#</a> CentOS / RHEL 7 : Booting process</h1>
<h2 id="introduction-of-systemd" tabindex="-1"><a class="header-anchor" href="#introduction-of-systemd" aria-hidden="true">#</a> Introduction of systemd</h2>
<p>systemd is the new system and service manager in CentOS/RHEL 7. It is backward compatible with SysV init scripts used by previous versions of RedHat Linux including RHEL 6. It replaces Upstart as the default initialization system.</p>
<p>The following steps summarize how the boot procedure happens in RHEL/CentOS 7.</p>
<ol>
<li>The computer’s BIOS performs POST.</li>
<li>BIOS reads the MBR for the bootloader.</li>
<li>GRUB 2 bootloader loads the vmlinuz kernel image.</li>
<li>GRUB 2 extracts the contents of the initramfs image.</li>
<li>The kernel loads driver modules from initramfs.</li>
<li>Kernel starts the system’s first process, systemd.</li>
<li>The systemd process takes over. It:</li>
</ol>
<ul>
<li>Reads configuration files from the /etc/systemd directory</li>
<li>Reads file linked by /etc/systemd/system/default.target</li>
<li>Brings the system to the state defined by the system target</li>
<li>Executes /etc/rc.local</li>
</ul>
<p><img src="/img/RHEL-CentOS-7-Boot-process-systemd.png" alt="pic"></p>
<h2 id="_1-post-power-on-self-test" tabindex="-1"><a class="header-anchor" href="#_1-post-power-on-self-test" aria-hidden="true">#</a> 1. POST (Power on Self Test)</h2>
<p>From the system firmware, which can be the modern Universal Extended Firmware Interface (UEFI) or the classical Basic Input Output System (BIOS), the Power-On Self-Test (POST) is executed, and the hardware that is required to start the system is initialized.</p>
<h2 id="_2-selecting-the-bootable-device-with-mbr" tabindex="-1"><a class="header-anchor" href="#_2-selecting-the-bootable-device-with-mbr" aria-hidden="true">#</a> 2. Selecting the bootable device (With MBR)</h2>
<p>– Master Boot Record (MBR) is the first 512 bytes of the boot drive that is read into memory by the BIOS.
– The next 64 bytes contain the partition table for the disk. The last two bytes are the “Magic Number” which is used for error detection.</p>
<p><img src="/img/MBR.png" alt="mbr"></p>
<p>– MBR discovers the bootable device and loads the GRUB2 boot loader into memory and transfers control over to it.</p>
<h2 id="_3-loading-the-boot-loader-grub2" tabindex="-1"><a class="header-anchor" href="#_3-loading-the-boot-loader-grub2" aria-hidden="true">#</a> 3. Loading the boot loader (GRUB2)</h2>
<p>– The default bootloader program used on RHEL 7 is GRUB 2. GRUB stands for GRand Unified Bootloader. GRUB 2 replaces the older GRUB bootloader also called as legacy GRUB.
– The GRUB 2 configuration file is located at /boot/grub2/grub.cfg (Do not edit this file directly).
– GRUB 2 menu-configuration settings are taken from /etc/default/grub when generating grub.cfg.
– Sample /etc/default/grub file :</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token comment"># cat /etc/default/grub</span>
<span class="token assign-left variable">GRUB_TIMEOUT</span><span class="token operator">=</span><span class="token number">5</span>
<span class="token assign-left variable">GRUB_DEFAULT</span><span class="token operator">=</span>saved
<span class="token assign-left variable">GRUB_DISABLE_SUBMENU</span><span class="token operator">=</span>true
<span class="token assign-left variable">GRUB_TERMINAL_OUTPUT</span><span class="token operator">=</span><span class="token string">"console"</span>
<span class="token assign-left variable">GRUB_CMDLINE_LINUX</span><span class="token operator">=</span><span class="token string">"rd.lvm.lv=rhel/swap crashkernel=auto rd.lvm.lv=rhel/root rhgb quiet net.ifnames=0"</span>
<span class="token assign-left variable">GRUB_DISABLE_RECOVERY</span><span class="token operator">=</span><span class="token string">"true"</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>– If changes are made to any of these parameters, you need to run grub2-mkconfig to re-generate the /boot/grub2/grub.cfg file.</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token comment"># grub2-mkconfig –o /boot/grub2/grub.cfg</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>– GRUB2 searches the compressed kernel image file also called as vmlinuz in the /boot directory.
– GRUB2 loads the vmlinuz kernel image file into memory and extracts the contents of the initramfs image file into a temporary, memory-based file system (tmpfs).
– The initial RAM disk (initrd) is an initial root file system that is mounted before the real root file system.</p>
<h3 id="initramfs" tabindex="-1"><a class="header-anchor" href="#initramfs" aria-hidden="true">#</a> initramfs</h3>
<p>– The job of the initial RAM file system is to preload the block device modules, such as for IDE, SCSI, or RAID, so that the root file system, on which those modules normally reside, can then be accessed and mounted.
– The initramfs is bound to the kernel and the kernel mounts this initramfs as part of a two-stage boot process.
– The dracut utility creates initramfs whenever a new kernel is installed.
– Use the lsinitrd command to view the contents of the image created by dracut:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token comment"># lsinitrd | less</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="_4-loading-the-kernel" tabindex="-1"><a class="header-anchor" href="#_4-loading-the-kernel" aria-hidden="true">#</a> 4. Loading the kernel</h2>
<p>– The kernel starts the systemd process with a process ID of 1 (PID 1).</p>
<p><img src="/img/systemd-first-process-started-with-PID-1-RHEL-7.png" alt="ps"></p>
<p>– It also loads the necessary driver modules from initrd image.
– The boot loader (GRUB2) may present a boot menu to the user, or can be configured to automatically start a default operating system.
– To load Linux, the kernel is loaded together with the initramfs. The initramfs contains kernel modules for all hardware that is required to boot, as well as the initial scripts required to proceed to the next stage of booting.
– On RHEL 7, the initramfs contains a complete operational system (which may be used for troubleshooting purposes).</p>
<h2 id="_5-starting-systemd" tabindex="-1"><a class="header-anchor" href="#_5-starting-systemd" aria-hidden="true">#</a> 5. Starting systemd</h2>
<p>– The kernel starts the systemd process with a process ID of 1 (PID 1).</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>root          <span class="token number">1</span>      <span class="token number">0</span>  <span class="token number">0</span> 02:10 ?        00:00:02 /usr/lib/systemd/systemd --switched-root --system --deserialize <span class="token number">23</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>– systemd is the first process that starts after the system boots, and is the final process that is running when the system shuts down.
– It controls the final stages of booting and prepares the system for use. It also speeds up booting by loading services concurrently.
– systemd reads the file linked by /etc/systemd/system/default.target (for example, /usr/lib/systemd/system/multi-user.target) to determine the default system target (equivalent to run level). The system target file defines the services that systemd starts.
– systemd allows you to manage various types of units on a system, including services (name.service) and targets (name.target), devices (name.device), file system mount points (name.mount), and sockets (name.socket).</p>
<p><strong>Comparision of SysV Run Levels and Target Units</strong></p>
<table>
<thead>
<tr>
<th>Run Level</th>
<th>Target Units</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>0</td>
<td>runlevel0.target, poweroff.target</td>
<td>Shut down and power off</td>
</tr>
<tr>
<td>1</td>
<td>runlevel1.target, rescue.target</td>
<td>Set up a rescue shell</td>
</tr>
<tr>
<td>2,3,4</td>
<td>runlevel[234].target, multi- user.target</td>
<td>Set up a nongraphical multi-user shell</td>
</tr>
<tr>
<td>5</td>
<td>runlevel5.target, graphical.target</td>
<td>Set up a graphical multi-user shell</td>
</tr>
<tr>
<td>6</td>
<td>runlevel6.target, reboot.target</td>
<td>Shut down and reboot the system</td>
</tr>
</tbody>
</table>
<p>systemd brings the system to the state defined by the system target, performing system initialization tasks such as:</p>
<ol>
<li>Setting the host name</li>
<li>Initializing the network</li>
<li>Initializing SELinux based on its configuration</li>
<li>Printing a welcome banner</li>
<li>Initializing the system hardware based on kernel boot arguments</li>
<li>Mounting the file systems, including virtual file systems such as the /proc file system</li>
<li>Cleaning up directories in /var</li>
<li>Starting swapping</li>
</ol>
</template>
